server:
  port: 8002

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.5:8848
        namespace: a2a75f73-be1a-4964-86d0-da3ca9521fd6
    gateway:
      discovery:
        locator:
          enabled: false # 关闭默认服务发现路由 # 表示完全手动控制路由规则，避免自动生成的路径干扰，适合需要自定义路径的场景。
      routes:
        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**
        - id: base-service
          uri: lb://base
          predicates:
            - Path=/base/**

#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    reactor.netty.http.client: DEBUG